apiVersion: v1
appVersion: "0.15.0-snapshot"
description: "Strimzi: Apache Kafka running on Kubernetes"
name: strimzi-kafka-operator
version: 0.15.0-snapshot
icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/master/documentation/logo/strimzi_logo.png
keywords:
- kafka
- queue
- stream
- event
- messaging
- datastore
- topic
home: https://strimzi.io/
sources:
- https://github.com/strimzi/strimzi-kafka-operator
maintainers:
- name: ppatierno
- name: scholzj
- name: tombentley