apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: testtopic1
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: testtopic2
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: testtopic3
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: testtopic4
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
